### CREATE
# "k_id_localidad"	"n_nombre_localidad"
# "01USQN"	"Usaquén"
# "02SUBA"	"Suba"
# "03CHPN"	"Chapinero"
# "04BOSA"	"Bosa"
# "05KENN"	"Kennedy"

### GET ALL
GET http://localhost:8080/localidad/find

### GET BY ID
GET http://localhost:8080/localidad/find/05KENN

### CREATE
POST http://localhost:8080/localidad/create
Content-Type: application/json

{
  "idLocalidad":"02MART",
  "nombreLocalidad":"Los Mártires"
}

### UPDATE
PUT http://localhost:8080/localidad/update/02MART
Content-Type: application/json

{
  "nombreLocalidad": "Los Martires"
}

### DELETE
DELETE http://localhost:8080/localidad/delete/02MART
